import type { Metadata } from "next";

// Canonical origin for every absolute URL the site emits (canonical tags,
// sitemap, robots.txt, Open Graph, JSON-LD). Set NEXT_PUBLIC_SITE_URL per
// environment; `||` (not `??`) so an empty value also falls back instead of
// crashing `new URL("")` at build time.
export const SITE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL || "https://standin-ai.vercel.app"
).replace(/\/+$/, "");

export const SITE_NAME = "StandIn";

export const OG_IMAGE_ALT =
  "StandIn — send an AI that actually knows you to your next AI interview";

// The shared social card generated by src/app/opengraph-image.tsx. Next only
// attaches that file automatically to pages that don't set their own
// `openGraph`/`twitter`, so pages that do must list it explicitly.
export const OG_IMAGE = { url: "/opengraph-image", width: 1200, height: 630, alt: OG_IMAGE_ALT };

/**
 * Per-page metadata with its own canonical and social card. Next merges
 * metadata shallowly, so a page that sets `openGraph` replaces the root
 * layout's whole `openGraph` object — this rebuilds it in full for each page
 * instead of every page silently sharing the homepage's title.
 */
export function pageMetadata({
  title,
  description,
  path,
  socialTitle,
}: {
  title: string;
  description: string;
  path: string;
  /** Title for social cards, without the " | StandIn" suffix. Defaults to `title`. */
  socialTitle?: string;
}): Metadata {
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      title: socialTitle ?? title,
      description,
      url: path,
      siteName: SITE_NAME,
      type: "website",
      images: [OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title: socialTitle ?? title,
      description,
      images: [OG_IMAGE],
    },
  };
}
